#!/bin/bash

## 1. 謎のとりあえずset -e or set -eu
set -e

# たいていの実行時エラーは変数の値の問題だから
# 変数をチェックする。
# if [ -z $var ]; then
#   echo '変数が設定されてません。' >&2 
#   return 1
# fi

## 2. ダメなところ関数を使わない。


## 3. オプションをなぜか分ける。
DF_OPTIONS="-k -l"

# ループの中に色々な処理が混ざっているのでデバッグが困難
# この処理を他でも使いたい、この処理を他の関数に分けたい、バグがあるから治したいというとき難しくなる。
# 
# dfとかこういうリストで見れるやつの
# 指定の列をグレップしたい場合、
# ループで%がある列を探すっていう。

割とプログラミング言語の延長線上でやりたがる。
# ループで処理しがち。
df $DF_OPTIONS | (
  # ヘッダー行だけ処理するために表示
  read line
  echo $line
  # 一行ずつ処理
  while read line; do
    line2=""
    
    # カラムごとに処理。
    echo $line | xargs -n 1 | (
      while read line2; do
        #  文法的な間違いがあった場合直すの難しい。[[]]
        if [[ $line2 == *"%"* ]] ; then
          
          # 大小比較のため、後ろの%を削除
          usage=${line2:0:-1}
          # ここがエラーになる可能性もある。
          if [ $usage -ge $THERESHOLD ]; then
            echo $line
          fi
        fi
      done
    )
  done
)
